TOPICS = [
    # SAT
    "SAT preparation tips",
    "SAT Math shortcuts",
    "SAT Reading strategies",
    "SAT Writing and Grammar tips",
    "How to get 1500+ in SAT",
    "SAT vocabulary building",
    "Best SAT study resources",
    "Digital SAT guide",
    "SAT practice routine",
    "Common SAT mistakes to avoid",
    "SAT time management tricks",
    "SAT score improvement plan",

    # IELTS
    "IELTS speaking strategies",
    "IELTS Writing Task 1 tips",
    "IELTS Writing Task 2 ideas",
    "IELTS Listening hacks",
    "IELTS Reading speed improvement",
    "How to get Band 8 in IELTS",
    "IELTS speaking cue card practice",
    "Common IELTS vocabulary",
    "IELTS grammar for high band score",
    "IELTS exam day tips",
    "Best IELTS preparation apps",
    "IELTS mistakes students make",

    # Study Abroad General
    "How to study abroad with scholarship",
    "Best countries for international students",
    "Affordable study abroad destinations",
    "Top scholarships for Bangladeshi students",
    "Student visa interview tips",
    "How to write SOP for university admission",
    "How to write a winning CV for study abroad",
    "Best undergraduate scholarships",
    "Fully funded scholarships guide",
    "Student life abroad",
    "How to choose the right university",
    "Part-time jobs for international students",

    # Italy
    "Study in Italy with scholarship",
    "Italy student visa process",
    "Top universities in Italy",
    "How to get DSU scholarship in Italy",
    "Living cost in Italy for students",
    "Best courses to study in Italy",
    "Italy scholarship without IELTS",
    "How to apply to Italian universities",
    "Student accommodation in Italy",
    "Italy vs Germany for international students",

    # Saudi Arabia
    "Study in Saudi Arabia with scholarship",
    "Top Saudi universities for international students",
    "Saudi Arabia student visa guide",
    "Islamic University Madinah scholarship",
    "King Saud University scholarship",
    "Living in Saudi Arabia as a student",
    "Fully funded Saudi scholarships",
    "Arabic language study in Saudi Arabia",
    "Engineering study in Saudi Arabia",
    "Saudi Arabia scholarship requirements",

    # China
    "Study in China with scholarship",
    "CSC Scholarship guide",
    "Top universities in China",
    "MBBS in China for international students",
    "Chinese Government Scholarship tips",
    "Study Mandarin in China",
    "Living cost in China for students",
    "China student visa process",
    "Best cities for students in China",
    "How to apply for Chinese universities",

    # Malaysia
    "Study in Malaysia for international students",
    "Malaysia scholarship opportunities",
    "Affordable universities in Malaysia",
    "Malaysia student visa guide",
    "Top private universities in Malaysia",
    "Living cost in Malaysia",
    "Engineering study in Malaysia",
    "Study in Malaysia without IELTS",
    "Student life in Malaysia",
    "Best courses in Malaysia",

    # Germany
    "Study in Germany for free",
    "Germany student visa process",
    "DAAD scholarship guide",
    "Top public universities in Germany",
    "Blocked account for Germany",
    "Living cost in Germany",
    "Study in Germany without IELTS",
    "Ausbildung opportunities in Germany",
    "German language preparation",
    "Part-time jobs in Germany for students",

    # Ireland
    "Study in Ireland with scholarship",
    "Ireland student visa guide",
    "Top universities in Ireland",
    "Living cost in Ireland",
    "Best courses in Ireland",
    "Work opportunities in Ireland after graduation",
    "Ireland vs Canada for students",
    "Scholarships in Irish universities",
    "Student accommodation in Ireland",
    "Tech careers in Ireland",

    # Technology
    "REST vs GraphQL",
    "Backend scaling basics",
    "Cloud computing fundamentals",
    "Introduction to DevOps",
    "Frontend vs Backend development",
    "Best programming languages to learn",
    "Cybersecurity basics",
    "AI tools for students",
    "Machine learning for beginners",
    "How APIs work",
    "Database design basics",
    "Web development roadmap",
    "Python projects for beginners",
    "Git and GitHub basics",

    # Freelancing & Career
    "Freelancing for beginners",
    "How to start freelancing on Fiverr",
    "Upwork profile optimization",
    "Best skills for online income",
    "Remote jobs for students",
    "How to become a virtual assistant",
    "Graphic design freelancing tips",
    "Video editing career guide",
    "Content writing for beginners",
    "Digital marketing basics",
    "How to earn online as a student",

    # Productivity & Student Life
    "Time management for students",
    "How to stay motivated while studying",
    "Daily routine for productive students",
    "Best study techniques",
    "Pomodoro technique for study",
    "How to avoid procrastination",
    "Note-taking strategies",
    "Best apps for students",
    "How to balance study and work",
    "Goal setting for students",
]